export const PATHS = {
  root: '/',
  search: '/search',
  searchProject: '/search/:id',
  projects: '/projects',
  project: '/projects/:id',
  addProject: '/add-project',
  chats: '/chats',
  dialog: '/chats/:id',
  profile: '/profile',
  profileMe: '/profile/me',
  notifications: '/notifications',
  notification: '/notifications/:id',
  settings: '/settings',
  profileSettings: '/settings/profile',
  notificationsSettings: '/settings/notifications',
  notFound: '/404',
  onboarding: '/onboarding',
};
