/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    /** Health */
    get: operations['health_health_get'];
  };
  '/api/rest/participants/': {
    /** Create Participant */
    post: operations['create_participant_api_rest_participants__post'];
  };
  '/api/rest/participants/{participant_id}': {
    /** Get Participant */
    get: operations['get_participant_api_rest_participants__participant_id__get'];
    /** Update Participant */
    post: operations['update_participant_api_rest_participants__participant_id__post'];
  };
  '/api/rest/positions/': {
    /** Get Positions */
    get: operations['get_positions_api_rest_positions__get'];
    /** Create Position */
    post: operations['create_position_api_rest_positions__post'];
  };
  '/api/rest/positions/{position_id}': {
    /** Remove Position */
    delete: operations['remove_position_api_rest_positions__position_id__delete'];
  };
  '/api/rest/positions/{position_id}/skills/': {
    /** Get Position Skills */
    get: operations['get_position_skills_api_rest_positions__position_id__skills__get'];
    /** Update Position Skills */
    post: operations['update_position_skills_api_rest_positions__position_id__skills__post'];
  };
  '/api/rest/projects/': {
    /** Get Projects */
    get: operations['get_projects_api_rest_projects__get'];
    /** Create Project */
    post: operations['create_project_api_rest_projects__post'];
  };
  '/api/rest/projects/{project_id}': {
    /** Get Project */
    get: operations['get_project_api_rest_projects__project_id__get'];
    /** Partial Update Project */
    patch: operations['partial_update_project_api_rest_projects__project_id__patch'];
  };
  '/api/rest/projects/{project_id}/avatar': {
    /** Get Project Avatar */
    get: operations['get_project_avatar_api_rest_projects__project_id__avatar_get'];
    /** Upload Project Avatar */
    post: operations['upload_project_avatar_api_rest_projects__project_id__avatar_post'];
    /** Delete Project Avatar */
    delete: operations['delete_project_avatar_api_rest_projects__project_id__avatar_delete'];
  };
  '/api/rest/projects/{project_id}/history': {
    /** History */
    get: operations['history_api_rest_projects__project_id__history_get'];
  };
  '/api/rest/reviews/': {
    /** Create Review */
    post: operations['create_review_api_rest_reviews__post'];
  };
  '/api/rest/users/{user_id}/statistic': {
    /** Get User Statistic */
    get: operations['get_user_statistic_api_rest_users__user_id__statistic_get'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Body_get_positions_api_rest_positions__get */
    Body_get_positions_api_rest_positions__get: {
      /** Specialization Ids */
      specialization_ids?: unknown;
      /** Skill Ids */
      skill_ids?: unknown;
    };
    /** Body_upload_project_avatar_api_rest_projects__project_id__avatar_post */
    Body_upload_project_avatar_api_rest_projects__project_id__avatar_post: {
      /**
       * Avatar
       * Format: binary
       */
      avatar: string;
    };
    /** CreateParticipantRequest */
    CreateParticipantRequest: {
      /**
       * Position Id
       * Format: uuid
       */
      position_id: string;
    };
    /** CreatePositionRequest */
    CreatePositionRequest: {
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /**
       * Specialization Id
       * Format: uuid
       */
      specialization_id: string;
    };
    /** CreateProjectRequest */
    CreateProjectRequest: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /**
       * Startline
       * Format: date-time
       */
      startline: string;
      /** Deadline */
      deadline?: string | null;
    };
    /** CreateReviewRequest */
    CreateReviewRequest: {
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Rate */
      rate: number;
      /** Text */
      text: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Version */
      version: string;
      /** Name */
      name: string;
    };
    /** ParticipantResponse */
    ParticipantResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Position Id
       * Format: uuid
       */
      position_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      status: components['schemas']['ParticipantStatusEnum'];
      /** Joined At */
      joined_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ParticipantStatusEnum
     * @enum {string}
     */
    ParticipantStatusEnum: 'request' | 'declined' | 'joined' | 'left';
    /** PositionListResponse */
    PositionListResponse: {
      /** Data */
      data: components['schemas']['PositionResponse'][];
      /** Page */
      page: number;
      /** Per Page */
      per_page: number;
      /** Total Pages */
      total_pages?: number | null;
      /** Total Items */
      total_items?: number | null;
    };
    /** PositionResponse */
    PositionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /**
       * Specialization Id
       * Format: uuid
       */
      specialization_id: string;
      /** Skills */
      skills: string[];
      /** Closed At */
      closed_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ProjectHistoryListResponse */
    ProjectHistoryListResponse: {
      /** Data */
      data: components['schemas']['ProjectHistoryResponse'][];
      /** Page */
      page: number;
      /** Per Page */
      per_page: number;
      /** Total Pages */
      total_pages?: number | null;
      /** Total Items */
      total_items?: number | null;
    };
    /** ProjectHistoryResponse */
    ProjectHistoryResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      status: components['schemas']['ProjectStatusEnum'];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ProjectListResponse */
    ProjectListResponse: {
      /** Data */
      data: components['schemas']['ProjectResponse'][];
      /** Page */
      page: number;
      /** Per Page */
      per_page: number;
      /** Total Pages */
      total_pages?: number | null;
      /** Total Items */
      total_items?: number | null;
    };
    /** ProjectPartialUpdateRequest */
    ProjectPartialUpdateRequest: {
      /** Status */
      status?: unknown;
    };
    /** ProjectResponse */
    ProjectResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /**
       * Startline
       * Format: date-time
       */
      startline: string;
      /** Deadline */
      deadline: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      status: components['schemas']['ProjectStatusEnum'];
    };
    /**
     * ProjectStatusEnum
     * @enum {string}
     */
    ProjectStatusEnum: 'preparation' | 'in_work' | 'finished';
    /** ReviewResponse */
    ReviewResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /**
       * From User Id
       * Format: uuid
       */
      from_user_id: string;
      /**
       * To User Id
       * Format: uuid
       */
      to_user_id: string;
      /** Rate */
      rate: number;
      /** Text */
      text: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** UpdateParticipantRequest */
    UpdateParticipantRequest: {
      status: components['schemas']['ParticipantStatusEnum'];
    };
    /** UserStatisticResponse */
    UserStatisticResponse: {
      /** Ownership Projects Count */
      ownership_projects_count: number;
      /** Participant Projects Count */
      participant_projects_count: number;
      /** Rate */
      rate: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  /** Create Participant */
  create_participant_api_rest_participants__post: {
    parameters: {
      header?: {
        Authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
        refresh_token?: string | null;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateParticipantRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ParticipantResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Get Participant */
  get_participant_api_rest_participants__participant_id__get: {
    parameters: {
      path: {
        participant_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ParticipantResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Update Participant */
  update_participant_api_rest_participants__participant_id__post: {
    parameters: {
      header?: {
        Authorization?: string | null;
      };
      path: {
        participant_id: string;
      };
      cookie?: {
        access_token?: string | null;
        refresh_token?: string | null;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateParticipantRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ParticipantResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Get Positions */
  get_positions_api_rest_positions__get: {
    parameters: {
      query?: {
        project_id?: unknown;
        is_closed?: unknown;
        project_query_text?: unknown;
        project_startline_ge?: unknown;
        project_startline_le?: unknown;
        project_deadline_ge?: unknown;
        project_deadline_le?: unknown;
        project_status?: unknown;
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        per_page?: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['Body_get_positions_api_rest_positions__get'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['PositionListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Create Position */
  create_position_api_rest_positions__post: {
    parameters: {
      header?: {
        Authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
        refresh_token?: string | null;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePositionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['PositionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Remove Position */
  remove_position_api_rest_positions__position_id__delete: {
    parameters: {
      header?: {
        Authorization?: string | null;
      };
      path: {
        position_id: string;
      };
      cookie?: {
        access_token?: string | null;
        refresh_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['PositionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Get Position Skills */
  get_position_skills_api_rest_positions__position_id__skills__get: {
    parameters: {
      path: {
        position_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': string[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Update Position Skills */
  update_position_skills_api_rest_positions__position_id__skills__post: {
    parameters: {
      header?: {
        Authorization?: string | null;
      };
      path: {
        position_id: string;
      };
      cookie?: {
        access_token?: string | null;
        refresh_token?: string | null;
      };
    };
    requestBody: {
      content: {
        'application/json': string[];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': string[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Get Projects */
  get_projects_api_rest_projects__get: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        per_page?: number;
        query_text?: unknown;
        owner_id?: unknown;
        user_id?: unknown;
        startline_ge?: unknown;
        startline_le?: unknown;
        deadline_ge?: unknown;
        deadline_le?: unknown;
        status?: unknown;
        position_skill_ids?: unknown;
        position_specialization_ids?: unknown;
        participant_user_ids?: unknown;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProjectListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Create Project */
  create_project_api_rest_projects__post: {
    parameters: {
      header?: {
        Authorization?: string | null;
      };
      cookie?: {
        access_token?: string | null;
        refresh_token?: string | null;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProjectRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Get Project */
  get_project_api_rest_projects__project_id__get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Partial Update Project */
  partial_update_project_api_rest_projects__project_id__patch: {
    parameters: {
      header?: {
        Authorization?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: {
        access_token?: string | null;
        refresh_token?: string | null;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectPartialUpdateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Get Project Avatar */
  get_project_avatar_api_rest_projects__project_id__avatar_get: {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': unknown;
          'image/*': string;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Upload Project Avatar */
  upload_project_avatar_api_rest_projects__project_id__avatar_post: {
    parameters: {
      header?: {
        Authorization?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: {
        access_token?: string | null;
        refresh_token?: string | null;
      };
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_project_avatar_api_rest_projects__project_id__avatar_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Delete Project Avatar */
  delete_project_avatar_api_rest_projects__project_id__avatar_delete: {
    parameters: {
      header?: {
        Authorization?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: {
        access_token?: string | null;
        refresh_token?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProjectResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** History */
  history_api_rest_projects__project_id__history_get: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Number of items per page */
        per_page?: number;
      };
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProjectHistoryListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Create Review */
  create_review_api_rest_reviews__post: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateReviewRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ReviewResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  /** Get User Statistic */
  get_user_statistic_api_rest_users__user_id__statistic_get: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['UserStatisticResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
