name: Deploy to dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        env:
          VITE_APP_BASE_URL: ${{ vars.STAGE_URL }}
        uses: appleboy/ssh-action@master
        if: contains(github.event.head_commit.message, 'chore:') == false
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          envs: VITE_APP_BASE_URL
          script: cd /var/www/front && git reset --hard HEAD && git clean  -d  -f .  && git pull --force && yarn --immutable && yarn build --mode development
