name: Deploy to prod

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        env:
          VITE_CLOSED: ${{ vars.VITE_CLOSED }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          envs: VITE_CLOSED
          script: cd /var/www/front-prod && git fetch origin && git reset --hard HEAD && git checkout -f ${{github.ref_name}} && yarn --immutable && VITE_CLOSED=$VITE_CLOSED yarn build
