name: Deploy to prod

on:
  push:
    tags:
      - '*'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: cd /var/www/front-prod && git checkout ${{github.ref_name}} && chmod +x ./deploy-prod.sh && ./deploy-prod.sh
