name: Deploy to dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == "chore:"* ]]; then
            echo "Commit message contains 'chore', skipping workflow."
            exit 0
          fi
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: cd /var/www/front && chmod +x ./deploy-dev.sh && ./deploy-dev.sh
