name: Test on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn
  tests:
    runs-on: ubuntu-18.04
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: yarn test
  eslint:
    runs-on: ubuntu-18.04
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run eslint
        run: yarn eslint
  tslint:
    runs-on: ubuntu-18.04
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tslint
        run: yarn tslint
  prettier:
    runs-on: ubuntu-18.04
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run prettier
        run: yarn prettier
  protect:
    runs-on: ubuntu-18.04
    needs: [tests, eslint, tslint, prettier]
    steps:
      - name: Protect branch
        run: echo "Branch is protected"
