name: Test on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn --immutable
      - name: Run checks
        run: yarn concurrently "yarn test" "yarn eslint" "yarn tslint" "yarn prettier" --raw
