name: Test on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  setup:
    runs-on: front
    steps:
      - name: Custom Checkout
        run: |
          if [ -d ${{ github.workspace }} ]; then
            echo "Fetching repository changes"
            cd ${{ github.workspace }}
            git fetch origin ${{ github.event.pull_request.head.ref }} --depth 1
            git reset --hard FETCH_HEAD
          else
            echo "Cloning repository"
            git clone --branch ${{ github.event.pull_request.head.ref }} --depth 1 git@github.com:${{ github.repository }} ${{ github.workspace }}
          fi
      - name: Install dependencies
        run: yarn

  tests:
    runs-on: front
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: yarn test
  eslint:
    runs-on: front
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run eslint
        run: yarn eslint
  tslint:
    runs-on: front
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tslint
        run: yarn tslint
  prettier:
    runs-on: front
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run prettier
        run: yarn prettier
  protect:
    runs-on: front
    needs: [tests, eslint, tslint, prettier]
    steps:
      - name: Protect branch
        run: echo "Branch is protected"
