name: Test on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable

  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: yarn test

  eslint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run eslint
        run: yarn eslint

  tslint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tslint
        run: yarn tslint

  prettier:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run prettier
        run: yarn prettier

  protect:
    runs-on: ubuntu-latest
    needs: [tests, eslint, tslint, prettier]
    steps:
      - name: Protect branch
        run: echo "Branch is protected"
